spring:
  application:
    name: hdService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.68.80:3306/bridgemonitor?useUnicode=true&amp;characterEncoding=UTF8&amp;useSSL=false
    username: root
    password: ENC(z/fKKSGy/h4JGnunOrV5wQ==)
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      uri: http://config:8750
      fail-fast: true
      username: user
      password: ${CONFIG_SERVER_PASSWORD:password}
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
server:
  port: 8601
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jasypt:
  encryptor:
    password: 123456
feign:
  compression:
    request:
      enable: true
      min-request-size: 2048
      mime-types: text/html,application/xml,application/json
    response:
      enable: true
management:
  security:
    enabled: false