spring:
  application:
    name: eurekaRegistry
server:
  port: 8761
eureka:
  instance:
    hostname: eurekaRegistry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
