spring:
  application:
    name: eurekaRegistry
server:
  port: 8761
security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
eureka:
  instance:
    hostname: eurekaRegistry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
