server:
  port: 8770
spring:
  application:
    name: zipkinServer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&amp;characterEncoding=UTF8&amp;useSSL=false
    username: root
    password: root
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
endpoints:
  actuator:
    enabled: true
  health:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false
flyway:
  locations: classpath:/db