server:
  port: 8800
spring:
  application:
    name: zuulGateway
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    hdservice: /hd/**
    rtmservice: /rtm/**
  ignored-services: '*'