spring:
  application:
    name: configCenter
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lennon0829/mySpringCloud/tree/master/spring-cloud
          search-paths: config-repo
server:
  port: 8750
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}