spring:
  application:
    name: configCenter
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lennon0829/mySpringCloud.git
          search-paths: spring-cloud/config-repo
    bus:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true