spring:
  application:
    name: monitorCenter
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://127.0.0.1:${turbine.stream.port}
  jackson:
    serialization:
      indent-output: true
server:
  port: 8602
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error
security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}
management:
  security:
    enabled: false
turbine:
  stream:
    port: 8603
endpoints:
  health:
    sensitive: false