spring:
  application:
    name: monitorCenter
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: http://127.0.0.1:${turbine.stream.port}
server:
  port: 8602
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error
turbine:
  stream:
    port: 8603
endpoints:
  actuator:
    enabled: true
  health:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false